name: dto_validator
description: Validator of dto
version: 1.0.0
homepage: https://github.com/shindakioku/dto_validator
author: firstlast <shindakioku@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
